version: '3'

services: 
  postgres:
    image: postgres:13-alpine
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xurl
    ports: 
      - 5432:5432
    volumes: 
      - ./ci/ddl:/docker-entrypoint-initdb.d
  
  redis:
    image: redis:6-alpine
    ports: 
      - 6379:6379

  prometheus:
    image: prom/prometheus:v2.32.1
    volumes:
      - ./ci/metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000
    volumes:
      - ./ci/metrics/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./ci/metrics/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./ci/metrics/grafana/xurl-dashboard.json:/etc/grafana/provisioning/dashboards/xurl/xurl-dashboard.json
      - ./ci/metrics/grafana/postgres-dashboard.json:/etc/grafana/provisioning/dashboards/xurl/postgres-dashboard.json
      - ./ci/metrics/grafana/redis-dashboard.json:/etc/grafana/provisioning/dashboards/xurl/redis-dashboard.json
  
  redis_exporter:
    image: oliver006/redis_exporter:v1.33.0-alpine
    environment:
      REDIS_ADDR: redis://redis:6379

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.10.0
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:postgres@postgres:5432/xurl?sslmode=disable
