global:
  scrape_interval: 5s

scrape_configs:
  - job_name: xurl_http
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets: ['host.docker.internal:8888']

  - job_name: redis_exporter
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: postgres_exporter
    static_configs:
      - targets: ['postgres_exporter:9187']
