{
 "title": "xurl",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(xurl_http_request_count_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Duration",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(xurl_http_response_duration_seconds_bucket[1m])))",
     "legendFormat": "90p"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"xurl_http\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    { "expr": "process_open_fds{}" }
   ]
  },
  {
   "title": "JVM GC Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_current{}" }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{} / 1024 / 1024",
     "legendFormat": "{{area}}"
    }
   ]
  }
 ]
}