name: ci tests

on:
  pull_request:
    branches: [ main ]

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      options: --user ${{ needs.configure.outputs.containerUser }}
    services:
      postgres:
        image: postgres:13-alpine
        env: 
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: xurl
        ports: 
          - 5432:5432
        volumes:
          - ${{github.workspace}}/ci/ddl:/docker-entrypoint-initdb.d
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6-alpine
        ports: 
          - 6379:6379
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: install graalvm
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.2.0"
          java-version: "java11"
      
      - name: xurl ci tests
        run: sbt ci
