name: ci tests

on:
  pull_request:
    branches: [ main ]

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env: 
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: xurl
        ports: 
          - 5432:5432
        volumes:
          - ${{github.workspace}}/ci/ddl:/docker-entrypoint-initdb.d
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:6-alpine
        ports: 
          - 6379:6379
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: install graalvm
        uses: keviswang/setup-graalvm@v1.0
        with:
          java-version: 11
          graalvm-version: 21.1.0
      
      - name: xurl ci tests
        run: sbt ci
